# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam Lee
email: mingli039@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am an oncoming web developer. I work mainly with
  HTML, CSS, JavaScript and PHP. I have developed many
  websites, web apps, and even some games as well.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mingli039.github.io/webucation" # the base hostname & protocol for your site
twitter_username: IA_Webucation
github_username:  mingli039

# Build settings
markdown: kramdown
